name: CI for Feature Branches

on:
  push:
    branches-ignore:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js (use Node 18)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Install Angular CLI globally
      - name: Install Angular CLI
        run: npm install -g @angular/cli@19

      # Build the project
      - name: Build Angular App
        run: npm run build